[tool.poetry]
name = "cryptopals"
version = "0.1.0"
description = ""
authors = ["T <tea.in.grams@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pycryptodome = "^3.18.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
